### ISSUE TITLE
lists in alphabetical order & possible use of tables

### ISSUE THREAD

**Issue by kera-cudmore** [codu-code/free-developer-resources#1]
1. Would it be worth listing the resources within each category alphabetically, to make looking for resources easier as this project grows?

2. I created something similar on a smaller scale for my intro to readme's with some resources and used tables - would this be useful as people could then provide a description of the resource (example below)?

![Screenshot 2023-03-13 at 12 04 19 pm](https://user-images.githubusercontent.com/92253071/224697297-24354168-0c10-4f98-b904-5c222858056b.png)

**Comment by NiallJoeMaher** [comment]
Yes! I spent a tonne of time making it alphabetical already, so please let me know what I missed or if I need clarification.  

I like the little image icons/descriptions for quickly finding things. It might be an upgrade soon. 🦾

**Comment by kera-cudmore** [comment]
Would be happy to pick this one up and add tables, descriptions etc for hacktoberfest if possible?

**Comment by NiallJoeMaher** [comment]
Yes, I'll add the label later or in the am. So fire ahead 🦾

**Comment by Eze-Bart** [comment]
nest the tables to add round corners
