### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by auxfuse** [codu-code/free-developer-resources#16]
This is an excellent first issue for someone who wants to assist in improving the workflow and management of incoming Pull Requests. 👏 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository ◀️◀️ some documentation to help whoever takes it on? 😏

**Comment by CBID2** [comment]
Hi @auxfuse! 😊 Is this issue still open? I want to try it. :)

**Comment by NiallJoeMaher** [comment]
It's all your @CBID2! 🚀

**Comment by CBID2** [comment]
Hey @NiallJoeMaher and @auxfuse! :) I created the pull template. Here it is: #27
