### ISSUE TITLE
Suggestion - Additional Readme Detail

### ISSUE THREAD

**Issue by Teemamin** [codu-code/free-developer-resources#20]
Suggestion:
- It might be worth adding a brief project description section to the Readme in order to make it clear to potential contributors at a glance.
-  Section on how to set up the project and create a pull request. I think that would be very helpful for people just starting off with GIT  and could potentially help with the intimidation of contributing to open source.

I am more than happy to write up the above.

**Comment by NiallJoeMaher** [comment]
Excellent ideas! We should break this into issues. 

This issue #1, tables were suggested for descriptions, and I agree! It would make it much easier to use.

**Comment by CBID2** [comment]
I can help too @NiallJoeMaher and @Teemamin !
