### ISSUE TITLE
Disability accommodation 

### ISSUE THREAD

**Issue by Eze-Bart** [codu-code/free-developer-resources#35]
I have discolexia, autism, and the one that makes me
Forget. Adhd. Will I have some sort of support in this project if I contribute?

**Comment by NiallJoeMaher** [comment]
We will try our best to accommodate but we might not have all of the time and support you might need as I'm not sure what level/or how to support all of your needs. 

I would suggest that you do your best to follow the guide and see where you get to and we can hopefully help you from there.

**Comment by Eze-Bart** [comment]
Nice accommodations. Got kicked out of discord for having an opinion. My review
https://www.linkedin.com/posts/bart-golaszewski_cod%C3%BA-you-suck-literally-a-closed-circle-activity-7115014098404130816-0nrQ?utm_source=share&utm_medium=member_ios

**Comment by NiallJoeMaher** [comment]
Closing because this guy is a troll...
